package com.example.android.infs3634;

/**
 * Created by PakinLertthamanon on 10/12/17.
 */

public enum Lesson {

    INTRO_TO_JAVA, ELEMENTARY_PROGRAMMING, SELECTIONS, LOOPS, METHODS, ARRAYS, OBJECTS,
    JAVA_FUNDAMENTALS, INHERITANCE, POLYMORPHISM, JAVAFX, EVENT_DRIVEN_PROGRAMMING, DATABASE, HCI,
    ANDROID_FUNDAMENTALS, ACTIVITIES, INTENTS, JSON, SQLLITE, CONTENT_PROVIDERS

}